application: nooglegoatbook-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images

- url: /app.crx
  static_files: static/app/app.crx
  upload: static/app/app.crx

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /
  script: index.app

- url: /view.*
  login: required
  script: view.app

- url: /api/notebook.*
  login: required
  script: notebook.app
